package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SubProjectRoot'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("SubProjectRoot")
    name = "SubProject_Root"
    url = "https://github.com/jpspringall/team-city-sub-projects"
    branch = "refs/heads/master"
    branchSpec = "%git.branch.specification%"
    agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_19a3f4f5d436b3ce0a7bf06f21adc120:-1:19d541a1-d9a1-4feb-9dcc-fe6c06b3a2fc"
    }
}))

